exclude: [CNAME, config, Gemfile, Gemfile.lock, lib, Procfile, Rakefile, sass]
name: Sketchnotes
permalink: /:categories/:title

markdown: redcarpet
redcarpet:
  extensions: ['smart', 'strikethrough']