[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      base-uri 'self'; \
      block-all-mixed-content; \
      child-src 'none'; \
      default-src 'self'; \
      font-src 'self' https://fonts.gstatic.com; \
      form-action 'none'; \
      frame-ancestors 'none'; \
      frame-src 'none'; \
      img-src * data:; \
      media-src *; \
      object-src 'none'; \
      script-src 'none'; \
      style-src 'self' https://fonts.googleapis.com; \
      worker-src 'none';\
    """
    Link = """
      <https://fonts.googleapis.com/>; rel=preconnect, \
      <https://fonts.gstatic.com/>; rel=preconnect
    """
    Referrer-Policy = "no-referrer-when-downgrade"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "0"

[[headers]]
  for = "/favicon.ico"
  [headers.values]
    Content-Type = "image/x-icon"

[[redirects]]
  from   = "https://sketchnotes-sixtwothree-org.netlify.com/*"
  to     = "https://sketchnotes.sixtwothree.org/:splat"
  status = 301
  force  = true
