title: sketchnotes.sixtwothree.org
description: Notes that aren’t really sketches.
author:
  name: Jason Garber
  url: https://sixtwothree.org
license:
  name: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
  url: https://creativecommons.org/licenses/by-nc-sa/4.0/
source:
  name: GitHub
  url: https://github.com/jgarber623/sketchnotes.sixtwothree.org
